/* LIVYA ADMIN access console. ADMIN-only employee provisioning and permissions. */
(function(){
  'use strict';
  const P=[['clients.view','View clients'],['clients.manage','Manage clients'],['reports.view','View reports'],['reports.manage','Manage reports'],['checkins.view','View check-ins'],['checkins.manage','Manage check-ins'],['notes.view','View notes'],['notes.manage','Manage notes'],['programs.view','View programmes'],['programs.manage','Manage programmes'],['diet.view','View diet plans'],['diet.manage','Manage diet plans'],['recipes.view','View recipes'],['recipes.manage','Manage recipes'],['files.view','View files'],['files.manage','Manage files'],['messages.view','View messages'],['messages.manage','Manage messages'],['audit.view','View audit log']];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=()=>`${window.LIVYA_SUPABASE_CONFIG?.url||''}/functions/v1/metabolic-api`;
  const req=async(path,opt={})=>{const b=window.LIVYA_BACKEND;const {data}=await b.client.auth.getSession();if(!data?.session?.access_token)throw Error('Session expired. Please sign in again.');const r=await fetch(`${api()}/${path}`,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`,...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j;};
  const perms=(current={})=>P.map(([k,l])=>`<label class="lap-perm"><input type="checkbox" data-perm="${esc(k)}" ${current[k]===true?'checked':''}>${esc(l)}</label>`).join('');
  const readPerms=root=>{const x={};root.querySelectorAll('[data-perm]').forEach(i=>x[i.dataset.perm]=i.checked);return x;};
  function css(){if(document.getElementById('lap-css'))return;const s=document.createElement('style');s.id='lap-css';s.textContent=`#livyaAdminButton{position:fixed;right:22px;bottom:22px;z-index:8000;border:1px solid rgba(22,45,36,.22);background:#fff;padding:11px 15px;border-radius:12px;box-shadow:0 8px 30px rgba(0,0,0,.12);font:700 11px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase;cursor:pointer;color:#162d24}#livyaAdminOverlay{position:fixed;inset:0;z-index:8100;background:rgba(18,25,22,.42);display:none;align-items:center;justify-content:center;padding:24px}#livyaAdminPanel{width:min(980px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 25px 80px rgba(0,0,0,.25);padding:26px}.lap-head{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}.lap-head h2{margin:0;font:700 23px Georgia,serif;color:#162d24}.lap-head p,.lap-meta{font:10px var(--mono,monospace);color:#69766f;margin-top:5px}.lap-close{border:0;background:#f2f4f1;border-radius:9px;width:34px;height:34px;cursor:pointer;font-size:20px}.lap-section{border-top:1px solid #e6e9e5;padding-top:18px;margin-top:18px}.lap-section h3{margin:0 0 12px;font:700 13px var(--mono,monospace);letter-spacing:.06em;text-transform:uppercase;color:#43524b}.lap-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.lap-form input,.lap-form select{width:100%;box-sizing:border-box;border:1px solid #d7ddd8;border-radius:9px;padding:11px;background:#fafbf9}.full{grid-column:1/-1}.lap-perms{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.lap-perm{display:flex;gap:8px;align-items:center;border:1px solid #e1e5e1;padding:9px;border-radius:9px;font:11px var(--mono,monospace)}.lap-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.lap-btn{border:1px solid #cfd7d1;background:#fff;border-radius:9px;padding:10px 13px;cursor:pointer;font-weight:700}.lap-btn.primary{background:#162d24;color:#fff}.lap-error{margin-top:10px;color:#8b2f2f;background:#fff1f1;border:1px solid #f0d1d1;border-radius:9px;padding:10px;font:11px var(--mono,monospace)}.lap-staff{display:grid;gap:10px}.lap-card{border:1px solid #e0e5e1;border-radius:12px;padding:13px;display:grid;grid-template-columns:1fr auto;gap:10px}.lap-tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.lap-tag{background:#f1f4f1;border-radius:99px;padding:4px 7px;font:9px var(--mono,monospace)}.lap-status{font:9px var(--mono,monospace);text-transform:uppercase}.lap-off{color:#8b2f2f}@media(max-width:700px){.lap-form,.lap-perms{grid-template-columns:1fr}.lap-card{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function shell(){const o=document.createElement('div');o.id='livyaAdminOverlay';o.innerHTML='<div id="livyaAdminPanel" role="dialog" aria-modal="true"><div class="lap-head"><div><h2>Staff access control</h2><p>ADMIN only · employee accounts, status and data permissions</p></div><button class="lap-close">×</button></div><div id="lapContent"></div></div>';document.body.appendChild(o);o.querySelector('.lap-close').onclick=()=>o.style.display='none';o.onclick=e=>{if(e.target===o)o.style.display='none';};return o;}
  const cards=staff=>staff.length?staff.map(s=>{const a=Object.entries(s.permissions||{}).filter(([,v])=>v===true).map(([k])=>`<span class="lap-tag">${esc(k)}</span>`).join('');return `<div class="lap-card"><div><b>${esc(s.full_name)}</b><div class="lap-meta">${esc(s.job_title||'Staff')} · ${esc(s.role)} · <span class="${s.status!=='ACTIVE'?'lap-off':''}">${esc(s.status)}</span></div><div class="lap-tags">${a||'<span class="lap-tag">No permissions</span>'}</div></div><button class="lap-btn" data-edit="${esc(s.user_id)}">Edit access</button></div>`;}).join(''):'<div class="lap-meta">No employee accounts yet.</div>';
  async function directory(){const root=document.getElementById('lapContent');root.innerHTML='<div class="lap-meta">Loading employee directory…</div>';try{const {data=[]}=await req('staff');root.innerHTML=`<div class="lap-section" style="border-top:0;padding-top:0;margin-top:0"><h3>Create employee</h3><form id="lapCreate" class="lap-form"><input name="fullName" placeholder="Employee full name" required><input name="email" type="email" placeholder="Work email" required><input name="phone" placeholder="Phone"><input name="jobTitle" value="Staff" placeholder="Job title"><input class="full" name="password" type="password" minlength="8" placeholder="Temporary password (8+ characters)" required><div class="full"><div class="lap-meta">Grant only the modules this employee needs. The database enforces these permissions.</div><div class="lap-perms">${perms()}</div></div><div class="full lap-actions"><button class="lap-btn primary">Create employee account</button></div></form><div id="lapCreateMsg"></div></div><div class="lap-section"><h3>Employee directory</h3><div class="lap-staff">${cards(data)}</div></div>`;document.getElementById('lapCreate').onsubmit=create;root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(data.find(s=>s.user_id===b.dataset.edit)));}catch(e){root.innerHTML=`<div class="lap-error">${esc(e.message)}</div>`;}}
  async function create(e){e.preventDefault();const f=e.currentTarget;try{const p=Object.fromEntries(new FormData(f).entries());p.permissions=readPerms(f);await req('staff',{method:'POST',body:JSON.stringify(p)});await directory();}catch(x){document.getElementById('lapCreateMsg').innerHTML=`<div class="lap-error">${esc(x.message)}</div>`;}}
  function edit(s){const root=document.getElementById('lapContent');root.innerHTML=`<div class="lap-section" style="border-top:0;padding-top:0;margin-top:0"><h3>Edit employee access</h3><form id="lapEdit" class="lap-form"><input name="fullName" value="${esc(s.full_name)}" required><input name="phone" value="${esc(s.phone||'')}" placeholder="Phone"><input class="full" name="jobTitle" value="${esc(s.job_title||'Staff')}" placeholder="Job title"><select name="status" class="full"><option ${s.status==='ACTIVE'?'selected':''}>ACTIVE</option><option ${s.status==='INACTIVE'?'selected':''}>INACTIVE</option></select><div class="full"><div class="lap-meta">Access permissions</div><div class="lap-perms">${perms(s.permissions||{})}</div></div><input class="full" name="password" type="password" minlength="8" placeholder="New password, leave blank to keep current"><div class="full lap-actions"><button type="button" class="lap-btn" id="lapBack">Back</button><button class="lap-btn primary">Save access</button></div></form><div id="lapEditMsg"></div></div>`;document.getElementById('lapBack').onclick=directory;document.getElementById('lapEdit').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const d=Object.fromEntries(new FormData(f).entries());const p={userId:s.user_id,fullName:d.fullName,phone:d.phone,jobTitle:d.jobTitle,status:d.status,permissions:readPerms(f)};if(d.password)p.password=d.password;try{await req('staff',{method:'PATCH',body:JSON.stringify(p)});await directory();}catch(x){document.getElementById('lapEditMsg').innerHTML=`<div class="lap-error">${esc(x.message)}</div>`;}};}
  function init(){if(!window.LIVYA_BACKEND?.client)return;css();const b=document.createElement('button');b.id='livyaAdminButton';b.type='button';b.textContent='Admin · Access';b.onclick=async()=>{const o=document.getElementById('livyaAdminOverlay')||shell();o.style.display='flex';await directory();};document.body.appendChild(b);const check=()=>{b.style.display=window.LIVYA_BACKEND?.role==='admin'?'block':'none';};check();setTimeout(check,500);setTimeout(check,1500);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
